"""
Unified LLM-driven Prefab chart generator.

Given any list-of-dicts, the LLM inspects the field names and sample values,
picks the most suitable Prefab chart type, and generates runnable Python code.

Decision rule (communicated to the LLM; also used in the deterministic fallback):
  - 3+ meaningful numeric fields  →  ScatterChart with z_axis (bubble chart)
  - 2 meaningful numeric fields   →  ScatterChart (x vs y scatter)

The output is always written to  mcp/generated_plot.py.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

try:
    from google import genai
except Exception:
    genai = None

HERE = Path(__file__).resolve().parent
GENERATED = HERE / "generated_plot.py"
MODEL = os.getenv("GEMINI_MODEL", "gemini-3.1-flash-lite-preview")
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY")) if genai is not None else None

# Fields that carry metadata / styling — never used as chart axes or labels.
_META = frozenset({
    "url", "channel_url", "video_id", "channel_id",
    "fill", "color_name", "bubble_color", "bubble_color_name",
    "_hover", "video_hover", "channel_hover",
})


def _numeric_fields(rows: list[dict]) -> list[str]:
    """Return names of int/float fields, skipping metadata keys."""
    if not rows:
        return []
    return [k for k, v in rows[0].items() if isinstance(v, (int, float)) and k not in _META]


def _label_field(rows: list[dict]) -> str:
    """Return the first string field that looks like a human-readable name."""
    if not rows:
        return ""
    for k, v in rows[0].items():
        if isinstance(v, str) and k not in _META:
            return k
    return ""


def _fallback_source(rows: list[dict], title: str) -> str:
    """Deterministic chart: 3+ numeric fields → bubble, 2 → scatter."""
    palette = ["#2563eb", "#16a34a", "#f59e0b", "#db2777", "#7c3aed", "#0891b2", "#dc2626"]
    color_names = ["Blue", "Green", "Amber", "Pink", "Violet", "Cyan", "Red"]

    num_fields = _numeric_fields(rows)
    lbl = _label_field(rows)

    chart_rows: list[dict] = []
    for idx, r in enumerate(rows):
        row = dict(r)
        label_val = r.get(lbl, f"Item {idx + 1}")
        url_val = r.get("url") or r.get("channel_url") or ""
        row["_hover"] = f"{label_val} ({url_val})" if url_val else str(label_val)
        row["fill"] = palette[idx % len(palette)]
        row["color_name"] = color_names[idx % len(color_names)]
        chart_rows.append(row)

    data_literal = json.dumps(chart_rows, ensure_ascii=False, indent=4)

    x = num_fields[0] if len(num_fields) > 0 else "x"
    y = num_fields[1] if len(num_fields) > 1 else "y"
    z = num_fields[2] if len(num_fields) > 2 else None
    hover_label = lbl or "Item"

    if z:
        axis_desc = f"X: {x}  ·  Y: {y}  ·  Bubble size: {z}"
        z_line = f'\n                    z_axis="{z}",'
    else:
        axis_desc = f"X: {x}  ·  Y: {y}"
        z_line = ""

    return f'''\
from prefab_ui.app import PrefabApp
from prefab_ui.components import Card, CardContent, CardHeader, CardTitle, Column, Muted, Row, Text
from prefab_ui.components.charts import ChartSeries, ScatterChart

# Generated by plot_prefab.py — do not edit by hand.
data = {data_literal}

with PrefabApp(css_class="max-w-5xl mx-auto p-6") as app:
    with Card():
        with CardHeader():
            CardTitle("{title}")
        with CardContent():
            with Column(gap=3):
                Muted("{axis_desc}")
                ScatterChart(
                    data=data,
                    series=[ChartSeries(data_key="_hover", label="{hover_label}")],
                    x_axis="{x}",
                    y_axis="{y}",{z_line}
                    height=480,
                    show_legend=True,
                    show_tooltip=True,
                    show_grid=True,
                )
                Muted("Legend:")
                with Column(gap=1):
                    for d in data:
                        with Row(gap=2, align="center"):
                            Text("●", css_class=f'text-[{{d["fill"]}}] text-base')
                            Text(f'{{d["_hover"]}} ({{d["color_name"]}})')
                Muted("Hover a point to see details.")
'''


def _extract_python(text: str) -> str:
    raw = (text or "").strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:python)?\s*", "", raw, flags=re.IGNORECASE)
        raw = re.sub(r"\s*```$", "", raw)
    return raw.strip()


def _looks_valid(source: str) -> bool:
    if not source.strip():
        return False
    forbidden = ["@app.page(", "def index(", "app = PrefabApp(", "style={"]
    required = ["from prefab_ui.app import PrefabApp", "with PrefabApp("]
    return not any(t in source for t in forbidden) and all(t in source for t in required)


def build_prefab_plot(rows: list[dict], title: str = "Data Plot") -> str:
    """
    Generate a Prefab app for any list-of-dicts dataset.

    The LLM inspects field names and sample values, then picks the best chart:
    - 3+ numeric fields → ScatterChart with z_axis (bubble chart)
    - 2 numeric fields  → ScatterChart (x vs y)
    Falls back to a deterministic version of the same logic if the LLM fails.
    """
    if client is None or not os.getenv("GEMINI_API_KEY"):
        return _fallback_source(rows, title)

    num_fields = _numeric_fields(rows)
    lbl = _label_field(rows)
    sample = rows[:3]

    prompt = f"""Generate a complete Python Prefab app for data visualization.

Dataset:
- {len(rows)} rows total
- Label field: "{lbl}"
- Numeric fields (in order): {num_fields}
- Sample rows (first 3 of {len(rows)}):
{json.dumps(sample, indent=2)}

Chart selection rule — choose based on how many numeric fields are present:
- 3 or more numeric fields  →  ScatterChart with x_axis, y_axis AND z_axis
  (z_axis makes bubbles whose size encodes a third dimension)
- Exactly 2 numeric fields  →  ScatterChart with x_axis and y_axis only (no z_axis)
Pick the 2 or 3 most meaningful numeric fields (prefer large-magnitude counts over
small ratios like score/0-1 values).

Requirements:
1. Use ONLY these imports:
   from prefab_ui.app import PrefabApp
   from prefab_ui.components import Card, CardContent, CardHeader, CardTitle, Column, Muted, Row, Text
   from prefab_ui.components.charts import ChartSeries, ScatterChart
2. Include a top-level `data` variable containing ALL {len(rows)} rows as a Python list literal
   (copy the exact values — do not truncate or summarise):
{json.dumps(rows, indent=2)}
3. Before the chart block, enrich each row in `data` with:
   - "_hover": human-readable label — combine "{lbl}" + url/channel_url if present
   - "fill": a distinct hex color per point from: #2563eb #16a34a #f59e0b #db2777 #7c3aed #0891b2 #dc2626
   - "color_name": matching color name (Blue, Green, Amber, Pink, Violet, Cyan, Red)
4. Use series=[ChartSeries(data_key="_hover", label="{lbl or 'Item'}")] for tooltip
5. Add a Muted() subtitle describing the axes (e.g. "X: subscribers · Y: views · Bubble size: videos")
6. Below the chart, show a colored legend: for each row render
   Text("●", css_class=f'text-[{{d["fill"]}}] text-base') then Text(d["_hover"])
7. Title: "{title}"

Output rules:
- Return ONLY valid Python — no markdown fences, no prose
- Use context-manager style:  with PrefabApp(...) as app:  ...
- Do NOT use @app.page, def index(), or app = PrefabApp(...)
"""
    try:
        response = client.models.generate_content(model=MODEL, contents=prompt)
        source = _extract_python(response.text or "")
        if not source:
            raise ValueError("empty response")
        if not _looks_valid(source):
            raise ValueError("invalid prefab syntax")
        compile(source, "<generated_plot>", "exec")
        return source
    except Exception:
        return _fallback_source(rows, title)
