"""
Generate a Prefab scatter chart for top videos: X = view count, Y = like count.

Run standalone:
  python video_views_prefab.py --channel https://www.youtube.com/@3blue1brown
  python video_views_prefab.py --channel https://www.youtube.com/@3blue1brown --no-serve
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

try:
    from google import genai
except Exception:
    genai = None

from channels_bubble_prefab import PrefabServer

HERE = Path(__file__).resolve().parent
GENERATED = HERE / "generated_video_views.py"
LOG_PATH = HERE / "prefab_video_views.log"
MODEL = os.getenv("GEMINI_MODEL", "gemini-3.1-flash-lite-preview")
client = genai.Client(api_key=os.getenv("GEMINI_API_KEY")) if genai is not None else None


def _build_video_chart_source_fallback(videos: list[dict]) -> str:
    palette = ["#2563eb", "#16a34a", "#f59e0b", "#db2777", "#7c3aed"]
    color_names = ["Blue", "Green", "Amber", "Pink", "Violet"]
    chart_rows: list[dict] = []
    for idx, v in enumerate(videos):
        row = dict(v)
        row["fill"] = palette[idx % len(palette)]
        row["color_name"] = color_names[idx % len(color_names)]
        row["video_hover"] = f'{v["title"]} ({v["url"]})'
        chart_rows.append(row)

    data_literal = json.dumps(chart_rows, ensure_ascii=False, indent=4)
    return f'''\
from prefab_ui.app import PrefabApp
from prefab_ui.components import Card, CardContent, CardHeader, CardTitle, Column, Muted, Row, Text
from prefab_ui.components.charts import ChartSeries, ScatterChart

# Generated by video_views_prefab.py — do not edit by hand; regenerate via the MCP tool.
data = {data_literal}

with PrefabApp(css_class="max-w-5xl mx-auto p-6") as app:
    with Card():
        with CardHeader():
            CardTitle("Top Videos — Views vs Likes")
        with CardContent():
            with Column(gap=3):
                Muted("X-axis: view count · Y-axis: like count · Each point = one video")
                ScatterChart(
                    data=data,
                    series=[ChartSeries(data_key="video_hover", label="Video")],
                    x_axis="view_count",
                    y_axis="like_count",
                    height=480,
                    show_legend=True,
                    show_tooltip=True,
                    show_grid=True,
                )
                Muted("Video → color mapping:")
                with Column(gap=1):
                    for d in data:
                        with Row(gap=2, align="center"):
                            Text("●", css_class=f\'text-[{{d["fill"]}}] text-base\')
                            Text(f\'{{d["title"]}} ({{d["color_name"]}})\')
                Muted("Hover a point to view video details.")
'''


def _extract_python_from_response(text: str) -> str:
    raw = (text or "").strip()
    if raw.startswith("```"):
        raw = re.sub(r"^```(?:python)?\s*", "", raw, flags=re.IGNORECASE)
        raw = re.sub(r"\s*```$", "", raw)
    return raw.strip()


def _looks_like_supported_video_chart_source(source: str) -> bool:
    if not source.strip():
        return False
    forbidden = ["@app.page(", "def index(", "app = PrefabApp(", "style={"]
    required = [
        "from prefab_ui.app import PrefabApp",
        "with PrefabApp(",
        "ScatterChart(",
        'x_axis="view_count"',
        'y_axis="like_count"',
    ]
    if any(tok in source for tok in forbidden):
        return False
    if not all(tok in source for tok in required):
        return False
    return True


def build_video_chart_source(videos: list[dict]) -> str:
    """Generate Prefab app source with LLM, falling back to a deterministic template."""
    if client is None or not os.getenv("GEMINI_API_KEY"):
        return _build_video_chart_source_fallback(videos)

    videos_json = json.dumps(videos, ensure_ascii=False, indent=2)
    prompt = f"""Generate a complete Python Prefab app file.

Requirements:
- Use ONLY these imports:
  from prefab_ui.app import PrefabApp
  from prefab_ui.components import Card, CardContent, CardHeader, CardTitle, Column, Muted, Row, Text
  from prefab_ui.components.charts import ChartSeries, ScatterChart
- Include a top-level variable named `data` set exactly to this JSON list:
{videos_json}
- Build one scatter chart with:
  - x_axis = view_count
  - y_axis = like_count
- Include tooltip context by using series=[ChartSeries(data_key="video_hover", label="Video")]
- Before chart render, enrich each row in `data` by adding:
  - video_hover = "<title> (<url>)"
  - fill / color_name fields for per-point coloring
- Bubble colors in the chart MUST use the exact per-row fill field.
- Under chart, show a video-color mapping list with a VISIBLY COLORED marker (●) next to each title.
- For each legend row, render: Text("●", css_class=f'text-[{{d["fill"]}}] text-base')
- Use PrefabApp + Card layout, with title "Top Videos — Views vs Likes".

Output rules:
- Return ONLY valid Python code.
- No markdown fences, no prose.
- Do NOT use `@app.page`, route decorators, or FastAPI-style handlers.
- Use only context-manager style: with PrefabApp(...) as app: ...
"""
    try:
        response = client.models.generate_content(model=MODEL, contents=prompt)
        source = _extract_python_from_response(response.text or "")
        if not source:
            raise ValueError("empty model response")
        if not _looks_like_supported_video_chart_source(source):
            raise ValueError("unsupported prefab syntax from model")
        compile(source, "<generated_video_chart>", "exec")
        return source
    except Exception:
        return _build_video_chart_source_fallback(videos)


def generate_app_from_videos(videos: list[dict]) -> None:
    """Write the generated Prefab app to GENERATED."""
    source = build_video_chart_source(videos)
    if not _looks_like_supported_video_chart_source(source):
        source = _build_video_chart_source_fallback(videos)
    compile(source, str(GENERATED), "exec")
    GENERATED.write_text(source, encoding="utf-8")


def main() -> None:
    import time

    ap = argparse.ArgumentParser(description="Generate Prefab views-vs-likes chart for a YouTube channel")
    ap.add_argument("--channel", required=True, help="YouTube channel URL or UC... id")
    ap.add_argument("--top-n", type=int, default=5, help="Number of top videos (default 5)")
    ap.add_argument("--no-serve", action="store_true", help="Only write generated file, don't serve")
    args = ap.parse_args()

    from youtube_video_stats import get_top_videos_with_stats

    print(f"Fetching top {args.top_n} videos for {args.channel} …")
    videos = get_top_videos_with_stats(args.channel, top_n=args.top_n)
    if not videos:
        raise SystemExit("No videos found.")

    print(f"Got {len(videos)} videos. Generating Prefab app …")
    generate_app_from_videos(videos)
    print(f"Wrote {GENERATED.name}")

    if args.no_serve:
        print("Skipping prefab serve (--no-serve). Run: prefab serve generated_video_views.py")
        return

    LOG_PATH.write_text("", encoding="utf-8")
    server = PrefabServer(GENERATED, LOG_PATH)
    print(f"Starting Prefab (logs → {LOG_PATH.name}) …")
    server.start()
    time.sleep(1.5)
    print("Open the URL printed by prefab (often http://127.0.0.1:5175) in your browser.")
    print("Press Ctrl+C to stop.\n")
    try:
        while True:
            time.sleep(1)
            if server._proc and server._proc.poll() is not None:
                print("Prefab process exited.")
                break
    except KeyboardInterrupt:
        pass
    finally:
        server.stop()


if __name__ == "__main__":
    main()
